server:
    port: 8080
    socketGateway: task-update

socket:
    update: task-update
    delete: task-delete
    add: task-add

db:
    type: mongodb
    synchronize: false
    useNewUrlParser: true
    useUnifiedTopology: true
    logging: true

jwt:
    expiresIn: 3600
    secret: topSecret
